# -*- coding: utf-8 -*-
"""MovieRecommendationSystem.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1LjR2MS29uRK_ciW41jXJTQ_MXQbhYV6a
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

df=pd.read_csv('dataset.csv')

df.shape

df.info()

df.describe()

df.isna().sum()

df['tags']=df['genre']+df['overview']

df.head()

movies=df[['id','title','tags']]

movies.head()

from sklearn.feature_extraction.text import CountVectorizer
from sklearn.metrics.pairwise import cosine_similarity
import pandas as pd




vectorizer = CountVectorizer(max_features=10000, stop_words='english')
vectors = vectorizer.fit_transform(movies['tags'].values.astype('U')).toarray()


sim = cosine_similarity(vectors)


def recommend(movie_name):

    movie_index = movies[movies['title'] == movie_name].index[0]


    distances = sim[movie_index]


    dist = sorted(list(enumerate(distances)), reverse=True, key=lambda x: x[1])


    print(f"\nMovies similar to '{movie_name}':\n")
    for i in dist[1:6]:
        print(movies.iloc[i[0]].title)


recommend("Dilwale Dulhania Le Jayenge")

